### ISSUE TITLE
Add reference to WebAssembly book

### ISSUE THREAD

**Issue by jstarry** [jetli/awesome-yew#3]
This book has a chapter on creating an app with Yew (I haven't reviewed it personally): https://pragprog.com/book/khrust/programming-webassembly-with-rust

**Comment by jetli** [comment]
This book was included once, I used this page: https://www.oreilly.com/library/view/programming-webassembly-with/9781680506846/
but I removed it in this commit: https://github.com/jetli/awesome-yew/commit/55b68bf2280452e70d4a0bdee869999bc742b9f8, because I cannot review it personally too, and I prefer online books.

I can add it back if you think it's useful.

**Comment by jetli** [comment]
Done, added it back: https://github.com/jetli/awesome-yew/commit/cc3df0f6257a08eba19d30e8cc6f061ec9b1aba8

**Comment by jstarry** [comment]
Yeah I think it's useful, thanks!
